"""R-parity tests: canonical engine output matches direct metafor::rma.mv at 1e-6.

Reference values are generated by an independent R invocation that:
  1. Loads AuditC_data directly from the DTA70 package (no Python intermediary)
  2. Constructs the bivariate long-format frame identically to canonical.py
  3. Calls rma.mv(yi, vi, mods=~outcome-1, random=~outcome|study, struct="UN", method="REML")
  4. Emits JSON with digits=15

The canonical engine was fixed (Task 10) to use digits=15 in its toJSON call so
that Python sees full float64 precision rather than the 4-decimal default.

Expected result: exact float64 agreement (diff == 0.0) for all five parameters,
well within the 1e-6 tolerance mandate.
"""
import json
from pathlib import Path
import pytest
from dta_floor_atlas.engines.canonical import fit_canonical
from dta_floor_atlas.corpus.loader import load_dta70_datasets

REFERENCE_DIR = Path(__file__).parent / "parity_fixtures"
TOL = 1e-6


@pytest.mark.parametrize("dataset_name,fixture_file", [
    # AuditC_data: k=14 alcohol-use-disorder screen, non-zero after CC,
    # converges cleanly with both rho and tau2 well-identified.
    ("AuditC_data", "auditc_data_metafor_reference.json"),
])
def test_canonical_matches_metafor_at_1e_minus_6(dataset_name, fixture_file):
    """Canonical engine matches independent metafor::rma.mv reference at tol 1e-6."""
    fixture_path = REFERENCE_DIR / fixture_file
    if not fixture_path.exists():
        pytest.skip(f"Reference fixture missing: {fixture_path}")

    ref = json.loads(fixture_path.read_text())

    target = next(
        (d for d in load_dta70_datasets() if d.dataset_id == dataset_name),
        None,
    )
    if target is None:
        pytest.skip(f"DTA70 install lacks {dataset_name}")

    fit = fit_canonical(target)
    assert fit.converged, (
        f"canonical failed on {dataset_name}: {fit.convergence_reason}"
    )

    se_diff = abs(fit.pooled_se - ref["pooled_se"])
    sp_diff = abs(fit.pooled_sp - ref["pooled_sp"])
    assert se_diff < TOL, (
        f"pooled_se: engine={fit.pooled_se!r} vs ref={ref['pooled_se']!r}, "
        f"|diff|={se_diff:.3e}"
    )
    assert sp_diff < TOL, (
        f"pooled_sp: engine={fit.pooled_sp!r} vs ref={ref['pooled_sp']!r}, "
        f"|diff|={sp_diff:.3e}"
    )

    if ref.get("rho") is not None and fit.rho is not None:
        rho_diff = abs(fit.rho - ref["rho"])
        assert rho_diff < TOL, (
            f"rho: engine={fit.rho!r} vs ref={ref['rho']!r}, |diff|={rho_diff:.3e}"
        )

    if ref.get("tau2_logit_se") is not None and fit.tau2_logit_se is not None:
        t2se_diff = abs(fit.tau2_logit_se - ref["tau2_logit_se"])
        assert t2se_diff < TOL, (
            f"tau2_logit_se: engine={fit.tau2_logit_se!r} vs "
            f"ref={ref['tau2_logit_se']!r}, |diff|={t2se_diff:.3e}"
        )

    if ref.get("tau2_logit_sp") is not None and fit.tau2_logit_sp is not None:
        t2sp_diff = abs(fit.tau2_logit_sp - ref["tau2_logit_sp"])
        assert t2sp_diff < TOL, (
            f"tau2_logit_sp: engine={fit.tau2_logit_sp!r} vs "
            f"ref={ref['tau2_logit_sp']!r}, |diff|={t2sp_diff:.3e}"
        )
